CREATE DATABASE IF NOT EXISTS tickets;
USE tickets;
CREATE TABLE IF NOT EXISTS AVAILS (
    DEP_DATE DATE NOT NULL PRIMARY KEY,
    SEATS INT NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOKINGS (
    BOOKID INT NOT NULL,
    USER_NAME VARCHAR(20) NOT NULL,
    FROM_LOC VARCHAR(20) NOT NULL,
    TO_LOC VARCHAR(20) NOT NULL,
    PH_NO BIGINT(10) NOT NULL,
    PREF VARCHAR(20) NOT NULL,
    NO_OF_SEATS INT NOT NULL,
    DATED DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PROFILE (
    UNAME VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    GENDER CHAR(1) NOT NULL,
    PH_NO BIGINT(10) NOT NULL,
    DOOR_NO INT NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    AREA VARCHAR(20) NOT NULL,
    CITY VARCHAR(20) NOT NULL,
    STATE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
    UNAME VARCHAR(20) NOT NULL,
    EMAIL_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS DETAILED_BOOKINGS (
    BOOKID INT NOT NULL,
    UNAME VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    GENDER CHAR(1) NOT NULL,
    COST REAL NOT NULL
);


-- insert data into the AVAILS table
SET @str = '2023-07-01';
SET @i = 1;
SET @r = 1;
SET @avails = 200;

FOR @i IN 1..30 DO
    SET @div = @i % 10;
    IF (@div = 0) THEN
        SET @str = CONCAT(SUBSTRING(@str, 1, 8), @r);
        SET @r = @r + 1;
    END IF;
    SET @str = CONCAT(SUBSTRING(@str, 1, 9), @div);
    INSERT INTO AVAILS VALUES (@str, @avails);
END FOR;

COMMIT;
