apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: ashwanthachu/mysql:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypassword
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: tickets
        ports: 
        - containerPort: 3306

---       
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
  type: ClusterIP